### PR TITLE
Feature/additional builders

### PR DESCRIPTION
**Pull request by codejanovic**
here are some suggestions i would like to share. looking forward to discuss the changes with you.

**what i did:**
- made builders truly immutable (except for the unmodifiable builder)
- provided a hopefully complete set of tests 
- splitted the concrete factories in its own classes (out of BuilderFactory), as the BuilderFactory should only provide the real common syntaxsugar like `a(...)` , `an(...)`, `of(...)` etc..

**whats still missing (in my view), is:**
- builders for keyvalue collections
- concrete unmodifiable builders (list, set etc)
- a wiki with a getting started guide and some code documentation

### CODE REVIEW

**Comment by casid** [comment]
Great additions to the builders project, will make everything much more mature I think.

A few things we should consider:
- API stability. An idea would be to move all builders provided by this framework in a stable/not likely to change class, for instance org.jusecase.Builders. This would allow to have one static import in a test (like with Mockito, Assert, ..) and be able to access all the builders provided.
- maybe find a way to quickly instantiate a default list in this Builders class (if you do not care, e.g. in unit tests) and to be able to be more specific if needed with arrayList / linkedList and so on.

I just noticed that travis ci failed, looks like there is a package in use that could not be discovered.

Let's talk about it tomorrow :-)

**Comment by codejanovic** [comment]
thanks for your feedback.

I also enabled travis builds for my fork, so hopefully i will recognize new build errors in the future :)
the build errors apparently do not seem to be hard to fix:

error | JDK | fix
-----|-----|-----
cannot find symbol Objects.requireNonNull | 7 | replace with own implementation
cannot find symbol Optional<T> | 8 | replace with own implementation
jdk.internal.util.xml.impl | 8 | delete import (a leftover)

**Comment by casid** [comment]
Awesome! I just created a develop branch. Let's see how this works out :-)

**Comment by casid** [comment]
Oh, I just upvoted this issue https://github.com/isaacs/github/issues/18 :+1: :-D

**Comment by codejanovic** [comment]
hehe ;-) for now i will do it with my bare hands :dancer:

**Pull request closed without merging**
